version: '3.8'

services:
  app:
    container_name: Snippets
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/snippetsDB
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "bun prisma generate && bun dev"

  db:
    container_name: snippets-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snippetsDB
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
