name: Snippet-backend

services:
    app:
        container_name: "snippet-backend"
        build:
            context: .
            dockerfile: Dockerfile

        # restart: unless-stopped
        ports:
            - "${PORT}:${PORT}"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/snippet-db?schema=public
        depends_on:
            - db

    db:
        image: postgres:13
        container_name: "snippet-db"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
